# Generated by Django 4.2.2 on 2023-06-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='group_field_name',
            new_name='group',
        ),
    ]
