# Generated by Django 4.2.2 on 2023-06-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_remove_trait_pets'),
        ('pets', '0002_rename_group_field_name_pet_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='trait',
            field=models.ManyToManyField(to='traits.trait'),
        ),
    ]
