# Generated by Django 4.2.2 on 2023-06-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_trait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='trait',
            new_name='traits',
        ),
    ]
