# Generated by Django 4.2.2 on 2023-06-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_trait_created_at'),
        ('pets', '0004_rename_trait_pet_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(related_name='pets', to='traits.trait'),
        ),
    ]
